on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8
      - name: Run tests
        run: pytest -q
      - name: Setup Database
        run: bash scripts/setup_db.sh
        env:
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_USER: ${{ secrets.RDS_USER }}
          RDS_DB: ${{ secrets.RDS_DB }}
          PGPASSWORD: ${{ secrets.RDS_PASS }}
      - name: Run Alembic migrations
        run: alembic upgrade head
      # TODO: add AWS deploy steps and Pages deploy
